### ISSUE TITLE
This module shoudl have duplicate Disabled.

### ISSUE THREAD

**Issue by becega** [LabVIEW-DCAF/Scan-Engine-Module#21]

**Comment by Beazurt** [comment]
@becega I think this functionality should go into the parent 'Edit Options' method. The parent method has access to the 'instances allowed' property and can default 'duplicate' to false if instances allowed is equal to 1. Can you think of any reason not to do it this way instead?

**Comment by Beazurt** [comment]
Added this feature to tag editor core.
