### ISSUE TITLE
Deleting a highlighted configuration channel removes the channel directly above it.

### ISSUE THREAD

**Issue by leesecho** [LabVIEW-DCAF/Scan-Engine-Module#29]
When attempting to remove a highlighted channel from the "Scan Engine Settings" table, I deleted the channel in the row above. As there is no "undo" feature, a workaround isn't possible.

**Comment by pollockm** [comment]
Replaces https://github.com/LabVIEW-DCAF/TagEditorCore/issues/283

**Comment by Beazurt** [comment]
This is a duplicate of issue #28

**Comment by pollockm** [comment]
:shipit:
