### ISSUE TITLE
Editor Node class dependency in Configuration class breaks application builds.

### ISSUE THREAD

**Issue by leesecho** [LabVIEW-DCAF/Scan-Engine-Module#30]
Scan Engine editor node.lvclass:**Protocol.ctl** is a dependency of Scan Engine configuration.lvclass:**Create Default Channel.vi**. This creates a dependency in the Runtime class, which has Configuration class dependencies.

Recommended fix:

1.  Move the Protocol.ctl type definition to the Configuration class (add "type definitions" Virtual Folder).

**Comment by pollockm** [comment]
Since this breaks RTEXE builds with Scan Engine, showstopper.

**Comment by leesecho** [comment]
I am building a package now in order to test (and hopefully verify) the fix.

**Comment by leesecho** [comment]
Fixed in commit 0ae17e4, RTEXE build success verified in build 68.

**Comment by pollockm** [comment]
Process request: please check that this new update does not break old configurations (any time we mess with typedefs or the contents of the configuration class, we have to be careful to verify that we did not break existing systems).  Once verified, we can push to VIPM.

**Comment by leesecho** [comment]
Old configuration file support was verified with the following test steps:

1. Downgrade DCAF Scan Engine Module to last published version (build 64).
2.  Launch DCAF Standard Editor
3. Create new configuration, add Local I/O>>Scan Engine module.
4. Add channels, map tags in Scan Engine module editor.
5. Save configuration file.
6. Upgrade DCAF Scan Engine Module to latest version (build 68).
7. Refresh DCAF Module plugins in DCAF Standard Editor (Tools>>Refresh Plugins).
8. Open configuration file, verify no error, channels and tags present.

No errors seen, configuration displayed as expected.

**Comment by pollockm** [comment]
:shipit:
