### ISSUE TITLE
Data Type options should not include those unsupported in hardware.

### ISSUE THREAD

**Issue by leesecho** [LabVIEW-DCAF/Scan-Engine-Module#31]
Channels can currently be edited to use any data type DCAF supports. In the case of the Scan Engine module, the only supported data types should be Double and Boolean, and probably should not include Array data types of _any_ type.

**Comment by pollockm** [comment]
The Scan Engine module also supports any item accessed via shared variables or UDVs, which can have any of those data types.  This is the reason why we have all of those data types supported.
