### ISSUE TITLE
Editor creates duplicate channels when importing from project.

### ISSUE THREAD

**Issue by ryanpopo** [LabVIEW-DCAF/Scan-Engine-Module#32]
If you add a few channels from a lvproj, and then use the import tool (possibly to get any remaining channels you don't already have) it adds duplicates of the channels already listed.

**Comment by Beazurt** [comment]
The root cause of this issue is related to this
https://github.com/LabVIEW-DCAF/DCAF-Project-Templates/issues/77

**Comment by Beazurt** [comment]
There is a fix here until the root cause is addressed. 4f0b6bf
