### ISSUE TITLE
Seperate Shared Variable Functionality from the Scan Engine

### ISSUE THREAD

**Issue by Beazurt** [LabVIEW-DCAF/Scan-Engine-Module#38]
Combining both shared variables and IOVs into one module has a few issues:
- Some users don't know Scan Engine can read from any variable URL
- Scan Engine can be optimized with bulk reads and writes for each module, but shared variables can't
- There should only be one instance of a Scan Engine module in a system, there can be multiple instances of a shared variable module (potentially one per library).
- Both likely want different error handling options as Scan Engine IO is typically much more critical than network IO

It might be possible to add a bunch of extra features to this one module, but my guess is that it would be too complicated and confusing. I think we should rip the Shared Variable functionality out of this and make it a separate module.

**Comment by becega** [comment]
I agree there would be some advantages of splitting it, the main issue with this move is that it would break backward compatibility if someone is already using the module to read shared variables.

**Comment by Beazurt** [comment]
Good point. We could still make a new variable module and leave the scan engine as-is. If we later decide to performance optimize we can either make a third module or have it be new settings in the existing module. Some of the challenges listed above can only be solved with two modules though.

**Comment by SimonRPSM** [comment]
As a quick note, I have been working on this module to have the IO variables use the Scanned Variable API. This would be done on cases where the system is reading every channel on a specific module. 

I think it may be worth splitting the module and having the Scan Engine module only work with this API and have another module for PSP variables, but until we decide to do this, the changes would be a good middle point (and the code reused anyhow).

**Comment by SimonRPSM** [comment]
I forgot to make a comment on this one. We ended up allowing for multiple Scan Engine Module instances and using a toggle to have only one override the Scan settings. This obviates the need for another module because I added the performance improvements to the generic one.
