### ISSUE TITLE
Import from Project errors with 1055 in LabVIEW 2017

### ISSUE THREAD

**Issue by The-deLEVoper** [LabVIEW-DCAF/Scan-Engine-Module#39]
We get error 1055 Object reference is invalid when trying to import from Project in the Scan Engine Module. 

![image](https://user-images.githubusercontent.com/27926243/27662108-2f9c98a2-5c22-11e7-8350-52705200c423.png)

It likely has to do with LabVIEW 2017 having a slight different hierarchy than previous versions.  

![image](https://user-images.githubusercontent.com/27926243/27662173-613564d4-5c22-11e7-979f-d60cbbdd13c9.png)

The Real-Time Scan Resources makes the modules one level lower in the project hierarchy, likely leading to this bug.

**Comment by becega** [comment]
Yes this is related to the change in the project. to support 2017 we need to add an extra case that if it finds real time scan resources to get the values inside of it. 
The vi that needs to be modified is: scan engine\editor node\Find All IO Variables.vi
While we are at updating this we might want to allow it to include importing libraries with shared variables that are in the project too.

**Comment by theSloopJohnB** [comment]
We can probably fix #4 at the same time as this.
