### ISSUE TITLE
Import feature should be improved to include variables in other containers (ex. EtherCAT)

### ISSUE THREAD

**Issue by knoxberry** [LabVIEW-DCAF/Scan-Engine-Module#44]
The import feature currently only supports importing IO variables from a single target in one container. The import feature should support a prompt or other method that allows the users to import other variables.

**Comment by becega** [comment]
This is already possible with the pull request #43 from LabVIEW-DCAF/Fixex42  …
Fixex42
I added that capability while fixing the bug.
