### ISSUE TITLE
2.2.0.26 Distribution Breaks Compilation for Linux RT

### ISSUE THREAD

**Issue by agomezNI** [LabVIEW-DCAF/Scan-Engine-Module#60]
After installing the 2.2.0.26 distribution, compiling an includes that uses the Scan Engine Module will cause the 1502 error.
https://knowledge.ni.com/KnowledgeArticleDetails?id=kA00Z000000P826SAC&l=en-US

Seems to be that this update is somehow calling into add glyphs.vi from the Glyphs Manager.lvlib, seems this is now being included in the dependencies and is the one the compiler is complaining about.

Problem was reproduced in 2 systems, my customer's and mine. 

I will look with more detail into the changes to identify the root of the problem. 

@SimonRPSM any thoughts?

**Comment by agomezNI** [comment]
Found out what the problem was. Seems that we recently added to string array and from string array for Import/Export. These VIs are using **classification to display permission.vi**  and **display permission to classification.vi**, which for some reason are part of the editor class and are creating the dependency between runtime and editor classes.

![image](https://user-images.githubusercontent.com/34285675/54316670-f17e8880-45a6-11e9-84b2-cfba93825be7.png)

For new modules we add these 2 VIs in the configuration class, probably to avoid this same problem. I will do the same as a fix for this.

FYI @becega , @SimonRPSM , @jacobson3

**Comment by jacobson3** [comment]
@agomezNI Good find. New dynamic modules actually have unit tests which check check that the runtime and config don't have editor dependencies but it doesn't look like they were ever added to this module.

I would suggest adding those tests so something similar doesn't happen again.

**Comment by jacobson3** [comment]
fixed in #61
