### ISSUE TITLE
Distribution 2.2.0.26 breaks compatibility with User Defined Variables

### ISSUE THREAD

**Issue by agomezNI** [LabVIEW-DCAF/Scan-Engine-Module#62]
Read/writes for IO variables are being grouped per module, which doesn't work for UDVs with different datatypes. 

FYI @jacobson3 , I will have to work on correcting this before making a new release in VIPM. I will work on a separate branch though, once you approve the pull-request I just made.

**Comment by mxrmesulog** [comment]
Hi AgomezNI,

I just update my DCAF application. I'm using scan engine and facing issue with my User defined variable. I have 3 I32 FPGA to Host and 1 Boolean Host to FPGA.
Do you have any easy workaround ?
I can easily change my boolean to i32 I think

Best regards

**Comment by agomezNI** [comment]
Hi @mxrmesulog,
Yes, that is the issue documented here. I would suggest you downgrade to the previous version available in VIPM which doesn't have this problem
